### ISSUE TITLE
[Feature] Add Foreign Key Constraint to team member table, so that referential integrity is automatically maintained.

### ISSUE THREAD

**Issue by karwootang-gft** [tranquilitybase-io/tb-db#18]
**Is your feature request related to a problem? Please describe.**
Add Foreign Key Constraint to team member table, so that referential integrity is automatically maintained.

**Describe the solution you'd like**

```
DROP TABLE IF EXISTS `teammember`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `teammember` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `userId` int(11) NOT NULL,
  `teamId` int(11) NOT NULL,
  `role` varchar(100) NOT NULL,
  `isActive` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  CONSTRAINT `FK_teammember_userId` FOREIGN KEY (`userId`) REFERENCES `user` (`id`),
  CONSTRAINT `FK_teammember_teamId` FOREIGN KEY (`teamId`) REFERENCES `team` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;
```

Describe alternatives you've considered
Without the FK Constraint, it's difficult to maintain referential integrity, but not impossible.

Additional context
Will apply to other tables as times goes on.

**Comment by Salles-FA** [comment]
@sandyasheri-gft please review this issue

**Comment by sandyasheri-gft** [comment]
Also I have added  FK for roleId columns
  CONSTRAINT `FK_teammember_roleId` FOREIGN KEY (`roleId`) REFERENCES `role` (`id`),
