### ISSUE TITLE
Change column 'ci' in 'activator' table 'ciId'  

### ISSUE THREAD

**Issue by sandyasheri-gft** [tranquilitybase-io/tb-db#24]
Store  Id of the ci instead of the name in 'activator' table

**Comment by sandyasheri-gft** [comment]
[https://github.com/tranquilitybase-io/tb-houston-service/issues/302](url)

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/tb-houston-service/issues/302
