### ISSUE TITLE
Change the 'load_lzlanvpc' to have only 'default' value initially

### ISSUE THREAD

**Issue by Salles-FA** [tranquilitybase-io/tb-db#45]
As part of the LandingZone setup, the admin user will select the size of network. Initially it will be XSmall.

1. on `dumps\load_lzlanvpc.sql` set only 'default' value
2. on `dumps\load_lzlanvpc_environment.sql` set the relationship accordingly.

**Comment by karwootang-gft** [comment]
https://github.com/tranquilitybase-io/tb-db/issues/47

**Comment by Salles-FA** [comment]
#46

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/tb-houston-service/issues/336
