### ISSUE TITLE
[Request] Add lzlanvpc.sharedVPCId column

### ISSUE THREAD

**Issue by karwootang-gft** [tranquilitybase-io/tb-db#47]
New db column: lzlanvpc.sharedVPCId column.
Make this the default VPC, make others inactive, only this one is active.

Retrieved from DaC using the DaC metadata endpoint.

**Comment by karwootang-gft** [comment]
https://github.com/tranquilitybase-io/tb-db/issues/45

**Comment by Salles-FA** [comment]
#46

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/tb-houston-service/issues/336
