### ISSUE TITLE
Create tables to maintain activator-cd and activator-environment relationships

### ISSUE THREAD

**Issue by sandyasheri-gft** [tranquilitybase-io/tb-db#58]
We need to create following tables with FK reference
1.activatorCD
2.activatorEnvironment

Change the existing table 
1.activator to reference id columns from above table

**Comment by sandyasheri-gft** [comment]
https://github.com/tranquilitybase-io/tb-houston-service/issues/351

**Comment by Salles-FA** [comment]
@sandyasheri-gft, 

Source control should be 1-1.

**Comment by sandyasheri-gft** [comment]
@Salles-FA , Ok 

> @sandyasheri-gft,
> 
> Source control should be 1-1.

Ok, Will not change SourceControl . Only CD and environments fields will be modified
