### ISSUE TITLE
Create system settings table

### ISSUE THREAD

**Issue by aivogft** [tranquilitybase-io/tb-db#88]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/TranquilityBase/issues/66

**Comment by Salles-FA** [comment]
https://github.com/tranquilitybase-io/tb-houston-service/issues/432
