### ISSUE TITLE
[feature] Update docker-compose files to use tb-db image 

### ISSUE THREAD

**Issue by karwootang-gft** [tranquilitybase-io/tb-db#9]
when tb-gcp is stable...

# tb-gcp
https://github.com/tranquilitybase-io/tb-gcp/blob/master/tb-gcp-tr/landingZone/eagle_console.yaml

# TranquilityBase
https://github.com/tranquilitybase-io/TranquilityBase/blob/master/docker-compose-integration.yml
https://github.com/tranquilitybase-io/TranquilityBase/blob/master/docker-compose-mock.yml

# tb-houston-service
https://github.com/tranquilitybase-io/tb-houston-service/blob/master/docker_compose_review.yml
https://github.com/tranquilitybase-io/tb-houston-service/blob/master/docker_compose_*.yml

# tb-eagle-console
https://github.com/tranquilitybase-io/tb-eagle-console/blob/master/docker-compose.yml
https://github.com/tranquilitybase-io/tb-eagle-console/blob/master/docker-compose.experimental.yml

**Comment by Salles-FA** [comment]
> when tb-gcp is stable...

when tb-db is stable...

**Comment by karwootang-gft** [comment]
Migration plan:
1. https://github.com/tranquilitybase-io/tb-houston-service/issues/277
2. https://github.com/tranquilitybase-io/tb-eagle-console/issues/192
3. https://github.com/tranquilitybase-io/TranquilityBase/issues/43
4. https://github.com/tranquilitybase-io/tb-gcp-dac/issues/107

**Comment by karwootang-gft** [comment]
tranquilitybase-io/tb-houston-service#277
tranquilitybase-io/tb-eagle-console#192
tranquilitybase-io/TranquilityBase#43
tranquilitybase-io/tb-gcp-dac#107

**Comment by karwootang-gft** [comment]
This main issue, I used to keep track of the issues in the other repos. 
All, the sub-issues are complete, so I can close this issue now.
