### ISSUE TITLE
Creation of a LZ-Admin and Mission Control Admin

### ISSUE THREAD

**Issue by aivogft** [tranquilitybase-io/tb-db#98]
- Change current isAdmin boolean to isLZAdmin, which will be able to see all screens under the “Administration menu”

- Add additional boolean isMCAdmin - Mission Control Admin will be able to Initialize the Activator Store, Initialize individual activators and Onboard them

**Comment by Salles-FA** [comment]
ref. https://github.com/tranquilitybase-io/tb-houston-service/issues/483
